from src.models.opticnet import OpticNet
from src.models.RETFound.vit import VisionTransformer
from src.models.RETFound.hf_vit import HFVIT
from src.models.DinoV2.dino_vit import DinoV2_siamese
from src.models.multiframe_latent_mae import MultiFrameLatentMAE
from src.models.visionfm import VisionFM
from src.models.mflmae import MFLM
from src.models.mae_st import vit_large_patch16
from src.models.VJepa import Vjepa
from src.models.Omnimae import vit_large_mae_finetune